name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      # Runs a single command using the runners shell
      - name: Print a greeting
        run: |
          echo If you see this, it is working.
          pwd
        
      # Build
      - name: Build
        run: dotnet build tModLoader.CodeAssist/tModLoader.CodeAssist.csproj --configuration Release
        
      # Publish
      - name: publish on version change
        uses: alirezanet/publish-nuget@v3.0.3
        with:
          PROJECT_FILE_PATH: tModLoader.CodeAssist/tModLoader.CodeAssist.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          # VERSION_STATIC: Bypasses version resolution; useful for external providers like Nerdbank.GitVersioning
          # TAG_COMMIT: true # Flag to enable / disalge git tagging
          # TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
          # PACKAGE_NAME: NuGet package name, required when it's different from project name. Defaults to project name
